# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e185a02cf762c0996a42e3a761a88442195da01d4860367614753229716f346df1a1932d0ad81c7a438b984a4a5c491e8d2f2d0d3e294e319416708036d2e8c0

test:
  secret_key_base: 6d2049545c37a2a38517346974a766eeea3b9c3ead9fee7ae51315fd280a5e9b6c001820871306487a6a710d76d7c835e9b7c0e4a8de7a619da54b7274ec92c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
